// Password protection with simple hash
// Hash generated by update_password.py

const PASSWORD_HASH = "4201191817";

// Simple hash function (must match Python version)
function hashPassword(password) {
  let hash = 0;
  for (let i = 0; i < password.length; i++) {
    const char = password.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = hash >>> 0; // Convert to 32-bit unsigned integer
  }
  return hash.toString();
}

function checkAuth() {
  const saved = localStorage.getItem("zno_authenticated");
  return saved === PASSWORD_HASH;
}

function logout() {
  localStorage.removeItem("zno_authenticated");
  window.location.reload();
}

function showAuthScreen() {
  document.body.innerHTML = `
    <div style="
      position: fixed;
      top: 0; left: 0; right: 0; bottom: 0;
      background: linear-gradient(135deg, #0d1117 0%, #1a1f2e 100%);
      display: flex;
      align-items: center;
      justify-content: center;
      font-family: Inter, sans-serif;
    ">
      <div style="
        background: #161b22;
        border: 1px solid #30363d;
        border-radius: 16px;
        padding: 3rem;
        max-width: 400px;
        width: 90%;
        box-shadow: 0 20px 60px rgba(0,0,0,0.5);
      ">
        <h1 style="color: #e6edf3; text-align: center; margin-bottom: 0.5rem;">
          🔒 ZNO Ukrainian Test Database
        </h1>
        <p style="color: #7d8590; text-align: center; margin-bottom: 2rem;">
          Access restricted to licensed users
        </p>
        <form id="authForm" style="display: flex; flex-direction: column; gap: 1rem;">
          <input 
            type="password" 
            id="authPassword" 
            placeholder="Enter access code"
            autocomplete="off"
            autofocus
            style="
              background: #21262d;
              border: 1px solid #30363d;
              border-radius: 8px;
              padding: 1rem;
              color: #e6edf3;
              font-size: 1rem;
              outline: none;
            "
          />
          <button type="submit" style="
            background: #f0b429;
            color: #0d1117;
            border: none;
            border-radius: 8px;
            padding: 1rem;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
          ">Access Database</button>
          <div id="authError" style="
            color: #f85149;
            font-size: 0.85rem;
            text-align: center;
            min-height: 1.2em;
          "></div>
        </form>
        <div style="
          margin-top: 2rem;
          padding-top: 2rem;
          border-top: 1px solid #30363d;
          text-align: center;
        ">
          <p style="color: #7d8590; font-size: 0.75rem;">Licensed for personal use only</p>
          <p style="color: #7d8590; font-size: 0.75rem;">For access, contact administrator</p>
        </div>
      </div>
    </div>
  `;

  document.getElementById("authForm").addEventListener("submit", (e) => {
    e.preventDefault();
    const input = document.getElementById("authPassword");
    const error = document.getElementById("authError");

    const inputHash = hashPassword(input.value);

    if (inputHash === PASSWORD_HASH) {
      localStorage.setItem("zno_authenticated", inputHash);
      window.location.reload();
    } else {
      error.textContent = "❌ Invalid access code";
      input.value = "";
    }
  });
}

// Run on page load
if (!checkAuth()) {
  showAuthScreen();
}
